apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 035604165710.dkr.ecr.eu-central-1.amazonaws.com/dev-frontend-diploma
  newTag: "vHESOYAM"
namespace: dev

resources:
- ../../../base/frontend


