apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
images:
- name: 035604165710.dkr.ecr.eu-central-1.amazonaws.com/backend-diploma
  newName: 035604165710.dkr.ecr.eu-central-1.amazonaws.com/backend-diploma
  newTag: 1.0.35
resources:
- ../../../base/backend
- ./secrets.yaml
