apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
images:
- name: 035604165710.dkr.ecr.eu-central-1.amazonaws.com/dev-backend-diploma
  newName: 035604165710.dkr.ecr.eu-central-1.amazonaws.com/dev-backend-diploma
  newTag: 1.0.12
- name: 035604165710.dkr.ecr.eu-central-1.amazonaws.com/prod-backend-diploma
  newName: 035604165710.dkr.ecr.eu-central-1.amazonaws.com/prod-backend-diploma
  newTag: 1.0.12
resources:
- ../../../base/backend
