version: "3.9"
   
services:
  pyapp:
    build: 
     context: ./backend/
     dockerfile: ./Dockerfile
    environment:
      - FLASK_ENV=development
      - DBHOST=123
      - DBUSER=mypyapp1
      - DBPASSWD=mypyapp1
      - DB_NAME=mypyapp1
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - pyapp

