name: CI\CD
on:
  push:
    branches:
      - development
      - main
    paths:
      - app/backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2